### ISSUE TITLE
Intermittent crashes of read1 on gc-perf6-dev

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#270]
This benchmark crashes (but not all the time) when run using code from this branch.

**Comment by justinethier** [comment]
TBD if `master` is also affected, but most likely it is...

**Comment by justinethier** [comment]
In at least one instance, the code actually ends up using the forwarded version (tag 10) of a port object, instead of the transported port object (tag 16):

```
(gdb) p *p
$12 = {hdr = {mark = 0 '\000', grayed = 0 '\000'}, tag = 10 '\n', fp = 0x7ffff6bfc020, mode = 1, flags = 1 '\001', line_num = 41, col_num = 2, buf_idx = 1024, tok_start = 0, tok_end = 0, tok_buf = 0x7b60d0 "x[(\367\377\177",
  tok_buf_len = 1024,
  mem_buf = 0x7cb140 "s book\n; contained several bugs that are corrected here.  These bugs are discussed\n; by Henry Baker, \"The Boyer Benchmark Meets Linear Logic\", ACM SIGPLAN Lisp\n; Pointers 6(4), October-December 1993, "...,
  mem_buf_len = 1024, read_len = 1024, str_bv_in_mem_buf = 0x0, str_bv_in_mem_buf_len = 0}
```

Obviously that fails because `fp` is assigned the address of an object on the heap and not a `FILE` pointer.

Here is the last part of the stack trace:

```
#0  0x00007ffff6f2f1dc in __GI__IO_fread (buf=0x7cb140, size=1, count=1024, fp=0x7ffff6bfc020) at iofread.c:37
#1  0x000000000053b31f in read_from_port (p=0x7fffffff9160) at runtime.c:6204
#2  0x000000000053b581 in _read_line_comment (p=0x7fffffff9160) at runtime.c:6248
#3  0x000000000053dbc9 in Cyc_io_read_token (data=0x7b64e0, cont=0x7fffffff8c80, port=0x7fffffff9160) at runtime.c:7033
#4  0x0000000000508660 in __lambda_19 (data=0x7b64e0, argc=2, _=0x7b3130 <c_73506>, k=0x7fffffff8c80, port=0x7fffffff9160) at scheme/read.c:1309
#5  0x0000000000501997 in __lambda_69 (data=0x7b64e0, argc=2, _=0x7b2ff0 <c_73516>, k_73238=0x7fffffff8d20, fp_7328_73158=0x7fffffff9160) at scheme/read.c:469
#6  0x0000000000509d6e in __lambda_9 (data=0x7b64e0, argc=1, self_73334=0x7fffffff8ec0, fp_7321_73149=0x7fffffff9160) at scheme/read.c:1481
#7  0x000000000050a237 in __lambda_7 (data=0x7b64e0, argc=1, self_73336=0x7fffffff8ea0, k_73221=0x7fffffff8ec0) at scheme/read.c:1498
#8  0x0000000000509bfb in __lambda_10 (data=0x7b64e0, argc=2, _=0x7b3170 <c_73437>, k_73217=0x7fffffff9020, args_7320_73148_raw=0x7fffffff9160) at scheme/read.c:1465
#9  0x0000000000414fc7 in __lambda_6 (data=0x7b64e0, argc=2, self_73218=0x7b1390 <c_73282>, k_73128=0x7fffffff90d0, in_732_7383=0x7fffffff9160) at read1.c:1544
#10 0x00000000004cb578 in __lambda_236 (data=0x7b64e0, argc=3, _=0x7b2ad0 <c_7314049>, k_734376=0x7fffffffa9f0, port_73287_732680=0x7fffffff9160, proc_73288_732681=0x7b1390 <c_73282>) at scheme/base.c:23921
#11 0x000000000050e0a2 in __lambda_0 (data=0x7b64e0, argc=3, _=0x7b3250 <c_7384>, k_7327=0x7fffffffa9f0, string_731_7313=0x7ffff65bf080, proc_732_7314=0x7b1390 <c_73282>) at scheme/file.c:640
#12 0x0000000000414e5a in __lambda_7 (data=0x7b64e0, argc=2, _=0x7b1430 <c_73280>, k_73126=0x7fffffffa9f0, input_731_7382=0x7ffff65bf080) at read1.c:1528
#13 0x0000000000414d27 in __lambda_8 (data=0x7b64e0, argc=1, self_73228=0x7fffffffa930, r_73146=0x7ffff65bf080) at read1.c:1521
#14 0x0000000000413ec5 in __lambda_17 (data=0x7b64e0, argc=2, self_73234=0x7b1350 <c_73360>, k_73160=0x7fffffffa930, x_7335_73100=0x7ffff65bf080) at read1.c:1397
#15 0x0000000000413c50 in __lambda_19 (data=0x7b64e0, argc=3, self_73235=0x7fffffffa890, k_73152=0x7fffffffa930, v_7336_73101=0x7fffffffa480, i_7337_73102=0x3) at read1.c:1375
#16 0x00000000005466e8 in do_dispatch (data=0x7b64e0, argc=3, func=0x413aff <__lambda_19>, clo=0x7fffffffa890, b=0x7fffffff9c70) at dispatch.c:6
#17 0x000000000053a22b in dispatch (data=0x7b64e0, argc=3, func=0x413aff <__lambda_19>, clo=0x7fffffffa890, cont=0x7fffffffa930, args=0x0) at runtime.c:5489
#18 0x0000000000538892 in apply (data=0x7b64e0, cont=0x7fffffffa930, func=0x7fffffffa890, args=0x7fffffffa110) at runtime.c:5044
#19 0x00000000004cc102 in __lambda_227 (data=0x7b64e0, argc=1, self_7311126=0x7fffffff9f90, r_734360=0x7b3390 <t_boolean>) at scheme/base.c:24046
#20 0x00000000004cc498 in __lambda_226 (data=0x7b64e0, argc=1, self_7311127=0x7fffffff9f70, k_734362=0x7fffffff9f90) at scheme/base.c:24057
#21 0x00000000004cc06a in __lambda_228 (data=0x7b64e0, argc=1, self_7311125=0x7fffffffa7b0, x_73281_732675=0x7fffffffa020) at scheme/base.c:24040
#22 0x00000000004ccc73 in __lambda_224 (data=0x7b64e0, argc=1, self_7311123=0x7fffffffa1e0, r_734349=0x7b33a0 <f_boolean>) at scheme/base.c:24100
#23 0x00000000004cceaa in __lambda_223 (data=0x7b64e0, argc=1, self_7311124=0x7fffffffa1c0, k_734353=0x7fffffffa1e0) at scheme/base.c:24108
#24 0x00000000004cc9d2 in __lambda_225 (data=0x7b64e0, argc=3, _=0x7b2b30 <c_7313977>, k_734348=0x7fffffffa7b0, args_73277_732672_raw=0x7fffffffa480) at scheme/base.c:24089
#25 0x00000000004141af in __lambda_15 (data=0x7b64e0, argc=1, self_73232=0x7fffffffa420, r_73156=0x3) at read1.c:1428
#26 0x0000000000414343 in __lambda_14 (data=0x7b64e0, argc=1, self_73233=0x7fffffffa400, k_73157=0x7fffffffa420) at read1.c:1436
#27 0x000000000041406d in __lambda_16 (data=0x7b64e0, argc=1, self_73231=0x7fffffffa700, r_73155=0x7fffffffa480) at read1.c:1424
#28 0x0000000000521950 in Cyc_list2vector (data=0x7b64e0, cont=0x7fffffffa700, l=0x7fffffffa520) at runtime.c:2950
```

**Comment by justinethier** [comment]
Once we protect against the forwarding pointer being introduced, one possible solution is to place any moved port objects into a buffer. The buffer could be cleared at the start of minor GC but the wakeup of a mutator that was cooperated for by the collector could be a special case that checks the buffer. For each port object in the buffer the object's fields are copied again to the heap object, ensuring that any updates to the port object on the stack made while the thread was doing I/O processing are preserved in the heap object.

**Comment by justinethier** [comment]
Also need to check all the places in the code where the runtime announces the mutator is blocked, and make sure there are no other cases where objects may be changed out from underneath the mutator.
