### ISSUE TITLE
gc_allocated_bytes: unexpected object 0xbf8a807c of type 2

### ISSUE THREAD

**Issue by justinethier** [justinethier/cyclone#45]
Observed the following error during compilation:

> cyclone cyclone.scm
> gc_allocated_bytes: unexpected object 0xbf8a807c of type 2
> make: *** [cyclone] Error 1

**Comment by justinethier** [comment]
It looks like `gc_allocated_bytes` may somehow be getting called for a stack object.

**Comment by justinethier** [comment]
This seems to have to do with an interaction between blocked/runnable functions and the collector. For example, the "long-running-process" example fails much faster now - sometimes with the above error sometimes not - after fixing `thread-sleep!` to use blocked/runnable.

These debugs seem to be printed shortly before each crash, although they are also printed several times and nothing crashes: 

    DEBUG - collector is cooperating for blocked mutator
    DEBUG - Call into gc_cont after collector coop

**Comment by justinethier** [comment]
EG:

    DEBUG - collector is cooperating for blocked mutator
    DEBUG - Call into gc_cont after collector coop
    DEBUG - after trace
    sweep heap 0xb71c8008, size = 6000000
    (50251)
    gc_allocated_bytes - passed value type 0xb75165c3 q=[0xb7513ce0, 10467] r=[0xb7518400, 2525600]

**Comment by justinethier** [comment]
From a verbose trace, a minor GC is started before sweep, but not finished until after. Could that have something to do with a closure that is incorrectly freed?

marked 0x7ffff7014aa0 1                                                          
DEBUG - after trace                                                              
started minor GC                                                                 
sweep heap 0x7ffff6d2d010, size = 6000000                                        
sweep is freeing unmarked obj: 0x7ffff6d2d060 with tag 8
...
sweep is freeing unmarked obj: 0x7ffff70181e0 with tag 0                         
sweep done, total_size = 6000000, total_free = 5877664, freed = 2909280, max_freed = 2953952, elapsed = 1
cleaning up any old thread data                                                  
alloc 0x7ffff6d2d060 size = 64, obj=0x7ffffffc0950, tag=8, mark=1
...
done with minor GC
....

Eventually this closure is unmarked and freed:

   sweep is freeing unmarked obj: 0x7ffff70167a0 with tag 8

Unfortunately it is still being used though:

    gc_mark_black mark buffer 0x7ffff70167a0, last_read = 70 last_write = 72         
    [New Thread 0x7ffff6d2c700 (LWP 4994)]                                           
    Program received signal SIGSEGV, Segmentation fault.                             
    [Switching to Thread 0x7ffff6d2c700 (LWP 4994)]                                  
    0x0000000000774960 in gc_mark_black (obj=0x7ffff70167a0) at gc.c:965             
    965>          gc_collector_mark_gray(obj, ((closureN) obj)->elts[i]);

**Comment by justinethier** [comment]
For what it's worth:

    (gdb) p *((closureN)obj)
    $5 = {hdr = {mark = 10676064, grayed = 0 '\000'}, tag = 8, fn = 0x4036f6 <__lambda_3>, 
             num_args = 1, num_elt = 3, elts = 0x7fff00000003}

**Comment by justinethier** [comment]
Updated gc.c to add pending_writes to last_write after the collector cooperates for a mutator. This seems to have helped a lot, but still received this error eventually when running `long-running-process`:

    gc_allocated_bytes: unexpected object 0xbf8a807c of type 2

**Comment by justinethier** [comment]
It seems in at least one case, the mutator and collector were both performing minor GC at the same time:

(gdb) bt
#0  0x76efc2d8 in raise (sig=2) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:37
#1  0x00368060 in gc_allocated_bytes (obj=0x7efeca6c, q=0x0, r=0x0) at gc.c:496
#2  0x00367cec in gc_try_alloc (h=0x767f6008, size=64, obj=0x7efeca6c "", thd=0x3c2280)
    at gc.c:418
#3  0x00367dc8 in gc_alloc (h=0x767f6008, size=64, obj=0x7efeca6c "", thd=0x3c2280,
    heap_grown=0x767b3d94) at gc.c:437
#4  0x00361624 in gc_move (obj=0x7efeca6c "", thd=0x3c2280, alloci=0x767b3d98,
    heap_grown=0x767b3d94) at runtime.c:2295
#5  0x00361938 in gc_minor (data=0x3c2280, low_limit=0x7efc200c, high_limit=0x7efff09c,
    cont=0x7efeca6c, args=0x0, num_args=0) at runtime.c:2375
#6  0x00369530 in gc_wait_handshake () at gc.c:1112
#7  0x0036971c in gc_collector () at gc.c:1179
#8  0x00369820 in collector_main (arg=0x3c1cec <collector_thread>) at gc.c:1228
#9  0x76ef2e90 in start_thread (arg=0x767b4460) at pthread_create.c:311
#10 0x76e7d128 in ?? () at ../ports/sysdeps/unix/sysv/linux/arm/nptl/../clone.S:92
   from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)


(gdb) bt
#0  0x76efa780 in __lll_lock_wait (futex=futex@entry=0x3c1cb4 <heap_lock>,
    private=<optimized out>) at ../ports/sysdeps/unix/sysv/linux/arm/nptl/lowlevellock.c:46
#1  0x76ef51a4 in __GI___pthread_mutex_lock (mutex=0x3c1cb4 <heap_lock>)
    at pthread_mutex_lock.c:79
#2  0x00367c28 in gc_try_alloc (h=0x767f6008, size=64, obj=0x7efef868 "", thd=0x3c2280)
    at gc.c:400
#3  0x00367dc8 in gc_alloc (h=0x767f6008, size=64, obj=0x7efef868 "", thd=0x3c2280,
    heap_grown=0x7efec994) at gc.c:437
#4  0x00361624 in gc_move (obj=0x7efef868 "", thd=0x3c2280, alloci=0x7efec998,
    heap_grown=0x7efec994) at runtime.c:2295
#5  0x00361ac8 in gc_minor (data=0x3c2280, low_limit=0x7efec9f7, high_limit=0x7efff09c,
    cont=0x76ae3300, args=0x3c24b0, num_args=1) at runtime.c:2393
#6  0x00369d30 in gc_mutator_thread_runnable (thd=0x3c2280, result=0x3c04b8 <t_boolean>)
    at gc.c:1365
#7  0x0018607c in __lambda_24 (data=0x3c2280, argc=2, _=0x767f7180, k=0x7efeca6c,
    timeout=0x7efeca58) at srfi/18.c:567
#8  0x00012e18 in __lambda_4 (data=0x3c2280, argc=1, self_7326=0x7efeccdc,
    r_7311=0x3c04d8 <Cyc_void_symbol>) at long-running-process.c:689
#9  0x0027fbec in __lambda_4 (data=0x3c2280, argc=1, self_7322=0x7efecc0c, r_7312=0x767f8720)
    at scheme/write.c:252
#10 0x000f1928 in __lambda_1185 (data=0x3c2280, argc=0, self_734982=0x7efecb2c)
    at scheme/base.c:40724
...

There must be a race condition...

**Comment by justinethier** [comment]
See:

23fd4268a327ec39b9db92e3ab4e5638c8669661

**Comment by justinethier** [comment]
Have not seen this crash again since the most recent set of changes.
